### ISSUE TITLE
ReferenceError: result is not defined

### ISSUE THREAD

**Issue by wrnx** [hueniverse/hawk#223]
This issue was introduced in #216 as result of minifying the `dist/browser.js` file. See babel/minify#594.

```
ERROR ReferenceError: result is not defined
    at Object.randomString (browser.js:1)
    at Object.header (browser.js:1)
    [...]
```

Relevant part of the `dist/browser.js` file prettified:
```javascript
// [...]
hawk.utils = {
  // [...]
  randomString: function randomString(c) {
    for (var d = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', e = d.length, f = [], g = 0; g < c; ++g)
      f[g] = d[Math.floor(Math.random() * e)];
    return result.join('')
  },
  // [...]
};
// [...]
```

**Comment by steffenmllr** [comment]
Same Error here. Since I'm using babel anyway `import Hawk from 'hawk/lib/browser';` fixed the issue for me.

**Comment by tkh44** [comment]
This bug has been fixed in https://github.com/babel/minify/pull/713 and needs to be released. Depending on their schedule I can change the build setup to use Uglify.

**Comment by edmorley** [comment]
This broke my project too, after updating from Hawk 6.0.2 to 7.0.5.

Reading the Babel issue/PR it seems the bug is limited to just the [babel-plugin-transform-merge-sibling-variables](https://www.npmjs.com/package/babel-plugin-transform-merge-sibling-variables) plugin.

As a workaround for now (that's less drastic than switching to Uglify), perhaps just plugin should be exlcuded via `.babelrc`?

**Comment by edmorley** [comment]
Hi! This isn't still exists in v7.0.6 (comparing `dist/browser.js` in `7.0.5` and `7.0.6` shows them to be identical).

Please can it be reopened?

**Comment by edmorley** [comment]
s/isn't/issue/

**Comment by hueniverse** [comment]
@tkh44 what needs to happen to fix it?
